const latitude = 40.741895
const longitude = -73.989308

const oldTracks = [{
    title: 'Freiburg',
    description: 'Garrett Semmelink: Violin<br>Our very first recording! Download the <a href="https://s3.amazonaws.com/sonicmultiplicities.audio/feed/downloads/SM_OLD001.flac">FLAC</a> or the <a href="https://s3.amazonaws.com/sonicmultiplicities.audio/feed/downloads/SM_OLD001.opus">OPUS</a>.',
    url: 'https://s3.amazonaws.com/sonicmultiplicities.audio/feed/SMOLD_001.mp3',
    categories: ['Music'],
    guid: 'SMOLD_001',
    author: 'Andrew Grathwohl',
    date: 'July 28, 2010',
    'lat': latitude,
    'long': longitude,
    enclosure: {
      url: 'https://s3.amazonaws.com/sonicmultiplicities.audio/feed/SM_OLD001.mp3',
      file: '../releases/SM_OLD001.mp3',
      type: 'audio/mpeg'
    },
    itunesSummary: 'Garrett Semmelink: Violin<br>Our very first recording! Download the <a href="https://s3.amazonaws.com/sonicmultiplicities.audio/feed/downloads/SM_OLD001.flac">FLAC</a> or the <a href="https://s3.amazonaws.com/sonicmultiplicities.audio/feed/downloads/SM_OLD001.opus">OPUS</a>.',
    itunesSubtitle: 'Our very first piece, back in 2010!',
    itunesDuration: 166,
    itunesExplicit: false,
    itunesKeywords: ['music', 'experimental', 'avant-garde', 'electroacoustic', 'computer', 'linux', 'audio'],
    itunesTitle: 'Freiburg',
    itunesImage: 'https://sonicmultiplicities.audio/triangle.png',
    itunesSeason: 2010,
    itunesEpisode: 1,
    itunesAuthor: 'Andrew Grathwohl',
    itunesEpisodeType: 'bonus'
},{
    title: 'Schadenfreude',
    description: 'Garrett Semmelink: Violin<br>Download the <a href="https://s3.amazonaws.com/sonicmultiplicities.audio/feed/downloads/SMOLD_002.flac">FLAC</a> or the <a href="https://s3.amazonaws.com/sonicmultiplicities.audio/feed/downloads/SMOLD_002.opus">OPUS</a>.',
    url: 'https://s3.amazonaws.com/sonicmultiplicities.audio/feed/SMOLD_002.mp3',
    categories: ['Music'],
    guid: 'SMOLD_002',
    author: 'Andrew Grathwohl',
    date: 'July 11, 2011',
    'lat': latitude,
    'long': longitude,
    enclosure: {
      url: 'https://s3.amazonaws.com/sonicmultiplicities.audio/feed/SMOLD_002.mp3',
      file: '../releases/SMOLD_002.mp3',
      type: 'audio/mpeg'
    },
    itunesSummary: 'Garrett Semmelink: Violin<br>Download the <a href="https://s3.amazonaws.com/sonicmultiplicities.audio/feed/downloads/SMOLD_002.flac">FLAC</a> or the <a href="https://s3.amazonaws.com/sonicmultiplicities.audio/feed/downloads/SMOLD_002.opus">OPUS</a>.',
    itunesSubtitle: 'Garrett Semmelink: Violin',
    itunesDuration: 204,
    itunesExplicit: false,
    itunesKeywords: ['music', 'experimental', 'avant-garde', 'electroacoustic', 'computer', 'linux', 'audio'],
    itunesTitle: 'Schadenfreude',
    itunesImage: 'https://sonicmultiplicities.audio/triangle.png',
    itunesSeason: 2011,
    itunesEpisode: 1,
    itunesAuthor: 'Andrew Grathwohl',
    itunesEpisodeType: 'bonus'
},{
    title: 'Maine',
    description: 'Garrett Semmelink: Violin<br>Unfortunately, due to data loss this track is not available for download.',
    url: 'https://s3.amazonaws.com/sonicmultiplicities.audio/feed/SMOLD_003.mp3',
    categories: ['Music'],
    guid: 'SMOLD_003',
    author: 'Andrew Grathwohl',
    date: 'February 10, 2012',
    'lat': latitude,
    'long': longitude,
    enclosure: {
      url: 'https://s3.amazonaws.com/sonicmultiplicities.audio/feed/SMOLD_003.mp3',
      file: '../releases/SMOLD_003.mp3',
      type: 'audio/mpeg'
    },
    itunesSummary: 'Garrett Semmelink: Violin<br>Unfortunately, due to data loss this track is not available for download.',
    itunesSubtitle: 'Garrett Semmelink: Violin',
    itunesDuration: 240,
    itunesExplicit: false,
    itunesKeywords: ['music', 'experimental', 'avant-garde', 'electroacoustic', 'computer', 'linux', 'audio'],
    itunesTitle: 'Maine',
    itunesImage: 'https://sonicmultiplicities.audio/triangle.png',
    itunesSeason: 2012,
    itunesEpisode: 1,
    itunesAuthor: 'Andrew Grathwohl',
    itunesEpisodeType: 'bonus'
},{
    title: 'Drowned',
    description: 'Garrett Semmelink: Violin<br>Unfortunately, due to data loss this track is not available for download.',
    url: 'https://s3.amazonaws.com/sonicmultiplicities.audio/feed/SMOLD_004.mp3',
    categories: ['Music'],
    guid: 'SMOLD_004',
    author: 'Andrew Grathwohl',
    date: 'February 10, 2012',
    'lat': latitude,
    'long': longitude,
    enclosure: {
      url: 'https://s3.amazonaws.com/sonicmultiplicities.audio/feed/SMOLD_004.mp3',
      file: '../releases/SMOLD_004.mp3',
      type: 'audio/mpeg'
    },
    itunesSummary: 'Garrett Semmelink: Violin<br>Unfortunately, due to data loss this track is not available for download.',
    itunesSubtitle: 'Garrett Semmelink: Violin',
    itunesDuration: 236,
    itunesExplicit: false,
    itunesKeywords: ['music', 'experimental', 'avant-garde', 'electroacoustic', 'computer', 'linux', 'audio'],
    itunesTitle: 'Drowned',
    itunesImage: 'https://sonicmultiplicities.audio/triangle.png',
    itunesSeason: 2012,
    itunesEpisode: 2,
    itunesAuthor: 'Andrew Grathwohl',
    itunesEpisodeType: 'bonus'
},{
    title: 'MAN QUA MAN (SEAMUS 2011 - Miami, FL)',
    description: 'Garrett Semmelink: Violin<br>Download the <a href="https://s3.amazonaws.com/sonicmultiplicities.audio/feed/downloads/SMOLD_005.flac">FLAC</a> or the <a href="https://s3.amazonaws.com/sonicmultiplicities.audio/feed/downloads/SMOLD_005.opus">OPUS</a>.',
    url: 'https://s3.amazonaws.com/sonicmultiplicities.audio/feed/SMOLD_005.mp3',
    categories: ['Music'],
    guid: 'SMOLD_005',
    author: 'Andrew Grathwohl',
    date: 'May 30, 2012',
    'lat': latitude,
    'long': longitude,
    enclosure: {
      url: 'https://s3.amazonaws.com/sonicmultiplicities.audio/feed/SMOLD_005.mp3',
      file: '../releases/SMOLD_005.mp3',
      type: 'audio/mpeg'
    },
    itunesSummary: 'Garrett Semmelink: Violin<br>Download the <a href="https://s3.amazonaws.com/sonicmultiplicities.audio/feed/downloads/SMOLD_005.flac">FLAC</a> or the <a href="https://s3.amazonaws.com/sonicmultiplicities.audio/feed/downloads/SMOLD_005.opus">OPUS</a>.',
    itunesSubtitle: 'Garrett Semmelink: Violin',
    itunesDuration: 346,
    itunesExplicit: false,
    itunesKeywords: ['music', 'experimental', 'avant-garde', 'electroacoustic', 'computer', 'linux', 'audio'],
    itunesTitle: 'MAN QUA MAN',
    itunesImage: 'https://sonicmultiplicities.audio/triangle.png',
    itunesSeason: 2012,
    itunesEpisode: 3,
    itunesAuthor: 'Andrew Grathwohl',
    itunesEpisodeType: 'bonus'
},{
    title: 'Untitled',
    description: 'Cosmo D: Cello<br>Download the <a href="https://s3.amazonaws.com/sonicmultiplicities.audio/feed/downloads/SMOLD_006.flac">FLAC</a> or the <a href="https://s3.amazonaws.com/sonicmultiplicities.audio/feed/downloads/SMOLD_006.opus">OPUS</a>.',
    url: 'https://s3.amazonaws.com/sonicmultiplicities.audio/feed/SMOLD_006.mp3',
    categories: ['Music'],
    guid: 'SMOLD_006',
    author: 'Andrew Grathwohl',
    date: 'July 06, 2012',
    'lat': latitude,
    'long': longitude,
    enclosure: {
      url: 'https://s3.amazonaws.com/sonicmultiplicities.audio/feed/SMOLD_006.mp3',
      file: '../releases/SMOLD_006.mp3',
      type: 'audio/mpeg'
    },
    itunesSummary: 'Cosmo D: Cello<br>Download the <a href="https://s3.amazonaws.com/sonicmultiplicities.audio/feed/downloads/SMOLD_006.flac">FLAC</a> or the <a href="https://s3.amazonaws.com/sonicmultiplicities.audio/feed/downloads/SMOLD_006.opus">OPUS</a>.',
    itunesSubtitle: 'Cosmo D: Cello',
    itunesDuration: 642,
    itunesExplicit: false,
    itunesKeywords: ['music', 'experimental', 'avant-garde', 'electroacoustic', 'computer', 'linux', 'audio'],
    itunesTitle: 'Untitled',
    itunesImage: 'https://sonicmultiplicities.audio/triangle.png',
    itunesSeason: 2012,
    itunesEpisode: 4,
    itunesAuthor: 'Andrew Grathwohl',
    itunesEpisodeType: 'bonus'
},{
    title: 'LEK4_AND',
    description: 'Garrett Semmelink: Steel violin<br>Download the <a href="https://s3.amazonaws.com/sonicmultiplicities.audio/feed/downloads/SMOLD_007.flac">FLAC</a> or the <a href="https://s3.amazonaws.com/sonicmultiplicities.audio/feed/downloads/SMOLD_007.opus">OPUS</a>.',
    url: 'https://s3.amazonaws.com/sonicmultiplicities.audio/feed/SMOLD_007.mp3',
    categories: ['Music'],
    guid: 'SMOLD_007',
    author: 'Andrew Grathwohl',
    date: 'Oct 19, 2012',
    'lat': latitude,
    'long': longitude,
    enclosure: {
      url: 'https://s3.amazonaws.com/sonicmultiplicities.audio/feed/SMOLD_007.mp3',
      file: '../releases/SMOLD_007.mp3',
      type: 'audio/mpeg'
    },
    itunesSummary: 'Garrett Semmelink: Steel violin<br>Download the <a href="https://s3.amazonaws.com/sonicmultiplicities.audio/feed/downloads/SMOLD_007.flac">FLAC</a> or the <a href="https://s3.amazonaws.com/sonicmultiplicities.audio/feed/downloads/SMOLD_007.opus">OPUS</a>.',
    itunesSubtitle: 'Garrett Semmelink: Steel violin',
    itunesDuration: 327,
    itunesExplicit: false,
    itunesKeywords: ['music', 'experimental', 'avant-garde', 'electroacoustic', 'computer', 'linux', 'audio'],
    itunesTitle: 'LEK4_AND',
    itunesImage: 'https://sonicmultiplicities.audio/triangle.png',
    itunesSeason: 2012,
    itunesEpisode: 5,
    itunesAuthor: 'Andrew Grathwohl',
    itunesEpisodeType: 'bonus'
},{
    title: 'Vasoconstriction',
    description: 'Garrett Semmelink: Violin<br>Download the <a href="https://s3.amazonaws.com/sonicmultiplicities.audio/feed/downloads/SMOLD_008.flac">FLAC</a> or the <a href="https://s3.amazonaws.com/sonicmultiplicities.audio/feed/downloads/SMOLD_008.opus">OPUS</a>.',
    url: 'https://s3.amazonaws.com/sonicmultiplicities.audio/feed/SMOLD_008.mp3',
    categories: ['Music'],
    guid: 'SMOLD_008',
    author: 'Andrew Grathwohl',
    date: 'Oct 23, 2014',
    'lat': latitude,
    'long': longitude,
    enclosure: {
      url: 'https://s3.amazonaws.com/sonicmultiplicities.audio/feed/SMOLD_008.mp3',
      file: '../releases/SMOLD_008.mp3',
      type: 'audio/mpeg'
    },
    itunesSummary: 'Garrett Semmelink: Violin<br>Download the <a href="https://s3.amazonaws.com/sonicmultiplicities.audio/feed/downloads/SMOLD_008.flac">FLAC</a> or the <a href="https://s3.amazonaws.com/sonicmultiplicities.audio/feed/downloads/SMOLD_008.opus">OPUS</a>.',
    itunesSubtitle: 'Garrett Semmelink: Violin',
    itunesDuration: 1028,
    itunesExplicit: false,
    itunesKeywords: ['music', 'experimental', 'avant-garde', 'electroacoustic', 'computer', 'linux', 'audio'],
    itunesTitle: 'Vasoconstriction',
    itunesImage: 'https://sonicmultiplicities.audio/triangle.png',
    itunesSeason: 2014,
    itunesEpisode: 1,
    itunesAuthor: 'Andrew Grathwohl',
    itunesEpisodeType: 'bonus'
},{
    title: 'Inertia',
    description: 'Garrett Semmelink: Violin<br>Download the <a href="https://s3.amazonaws.com/sonicmultiplicities.audio/feed/downloads/SMOLD_009.flac">FLAC</a> or the <a href="https://s3.amazonaws.com/sonicmultiplicities.audio/feed/downloads/SMOLD_009.opus">OPUS</a>.',
    url: 'https://s3.amazonaws.com/sonicmultiplicities.audio/feed/SMOLD_009.mp3',
    categories: ['Music'],
    guid: 'SMOLD_009',
    author: 'Andrew Grathwohl',
    date: 'Oct 26, 2014',
    'lat': latitude,
    'long': longitude,
    enclosure: {
      url: 'https://s3.amazonaws.com/sonicmultiplicities.audio/feed/SMOLD_009.mp3',
      file: '../releases/SMOLD_009.mp3',
      type: 'audio/mpeg'
    },
    itunesSummary: 'Garrett Semmelink: Violin<br>Download the <a href="https://s3.amazonaws.com/sonicmultiplicities.audio/feed/downloads/SMOLD_009.flac">FLAC</a> or the <a href="https://s3.amazonaws.com/sonicmultiplicities.audio/feed/downloads/SMOLD_009.opus">OPUS</a>.',
    itunesSubtitle: 'Garrett Semmelink: Violin',
    itunesDuration: 789,
    itunesExplicit: false,
    itunesKeywords: ['music', 'experimental', 'avant-garde', 'electroacoustic', 'computer', 'linux', 'audio'],
    itunesTitle: 'Inertia',
    itunesImage: 'https://sonicmultiplicities.audio/triangle.png',
    itunesSeason: 2014,
    itunesEpisode: 2,
    itunesAuthor: 'Andrew Grathwohl',
    itunesEpisodeType: 'bonus'
},{
    title: 'Miasma',
    description: 'Garrett Semmelink: Violin<br>Download the <a href="https://s3.amazonaws.com/sonicmultiplicities.audio/feed/downloads/SMOLD_010.flac">FLAC</a> or the <a href="https://s3.amazonaws.com/sonicmultiplicities.audio/feed/downloads/SMOLD_010.opus">OPUS</a>.',
    url: 'https://s3.amazonaws.com/sonicmultiplicities.audio/feed/SMOLD_010.mp3',
    categories: ['Music'],
    guid: 'SMOLD_010',
    author: 'Andrew Grathwohl',
    date: 'December 12, 2014',
    'lat': latitude,
    'long': longitude,
    enclosure: {
      url: 'https://s3.amazonaws.com/sonicmultiplicities.audio/feed/SMOLD_010.mp3',
      file: '../releases/SMOLD_010.mp3',
      type: 'audio/mpeg'
    },
    itunesSummary: 'Garrett Semmelink: Violin<br>Download the <a href="https://s3.amazonaws.com/sonicmultiplicities.audio/feed/downloads/SMOLD_010.flac">FLAC</a> or the <a href="https://s3.amazonaws.com/sonicmultiplicities.audio/feed/downloads/SMOLD_010.opus">OPUS</a>.',
    itunesSubtitle: 'Garrett Semmelink: Violin',
    itunesDuration: 712,
    itunesExplicit: false,
    itunesKeywords: ['music', 'experimental', 'avant-garde', 'electroacoustic', 'computer', 'linux', 'audio'],
    itunesTitle: 'Miasma',
    itunesImage: 'https://sonicmultiplicities.audio/triangle.png',
    itunesSeason: 2014,
    itunesEpisode: 3,
    itunesAuthor: 'Andrew Grathwohl',
    itunesEpisodeType: 'bonus'
},{
    title: 'Labor',
    description: 'Garrett Semmelink: Violin<br>Download the <a href="https://s3.amazonaws.com/sonicmultiplicities.audio/feed/downloads/SMOLD_011.flac">FLAC</a> or the <a href="https://s3.amazonaws.com/sonicmultiplicities.audio/feed/downloads/SMOLD_011.opus">OPUS</a>.',
    url: 'https://s3.amazonaws.com/sonicmultiplicities.audio/feed/SMOLD_011.mp3',
    categories: ['Music'],
    guid: 'SMOLD_011',
    author: 'Andrew Grathwohl',
    date: 'December 17, 2014',
    'lat': latitude,
    'long': longitude,
    enclosure: {
      url: 'https://s3.amazonaws.com/sonicmultiplicities.audio/feed/SMOLD_011.mp3',
      file: '../releases/SMOLD_011.mp3',
      type: 'audio/mpeg'
    },
    itunesSummary: 'Garrett Semmelink: Violin<br>Download the <a href="https://s3.amazonaws.com/sonicmultiplicities.audio/feed/downloads/SMOLD_011.flac">FLAC</a> or the <a href="https://s3.amazonaws.com/sonicmultiplicities.audio/feed/downloads/SMOLD_011.opus">OPUS</a>.',
    itunesSubtitle: 'Garrett Semmelink: Violin',
    itunesDuration: 765,
    itunesExplicit: false,
    itunesKeywords: ['music', 'experimental', 'avant-garde', 'electroacoustic', 'computer', 'linux', 'audio'],
    itunesTitle: 'Labor',
    itunesImage: 'https://sonicmultiplicities.audio/triangle.png',
    itunesSeason: 2014,
    itunesEpisode: 4,
    itunesAuthor: 'Andrew Grathwohl',
    itunesEpisodeType: 'bonus'
}]

module.exports = {
  feed: {
    title: '▲ Presents: Sonic Multiplicities',
    description: 'The official podcast feed for works of Sonic Multiplicities performed by ▲. Each episode presents a complete, unmodified Sonic Multiplicities session, heard here exactly as it was performed at The Cathedral, ▲\'s Brooklyn, NY headquarters. Join us for an intimate and intense journey through the roaring musical psyches of some of NYC\'s finest free improvisers! Highly recommended for fans of electroacoustic music, free & avant-garde jazz, noise music, the violin and the SuperCollider programming language.',
    feedUrl: 'https://sonicmultiplicities.audio/feed.xml',
    siteUrl: 'https://sonicmultiplicities.audio',
    imageUrl: 'https://sonicmultiplicities.audio/triangle.png',
    author: 'Andrew Grathwohl',
    managingEditor: 'Andrew Grathwohl',
    copyright: '2019 Sacred Data, LLC',
    pubDate: 'October 13, 2019 04:00:00 GMT',
    ttl: '60',
    language: 'en',
    categories: ['Music'],
    itunesOwner: { name: 'Andrew Grathwohl', email: 'sm@grathwohl.me' },
    itunesImage: 'https://sonicmultiplicities.audio/triangle.png',
    itunesExplicit: false,
    itunesCategory: [
      { "text": "Arts", "subcats": [ { "text": "Performing Arts" } ] },
      { "text": "Music", "subcats": [ { "text": "Music Commentary" }, { "text": "Music Interviews" } ] },
      { "text": "Society & Culture", "subcats": [ { "text": "Personal Journals" } ] }
    ],
    itunesAuthor: 'Andrew Grathwohl'
  },
  items: [{
    title: 'SM000: Introduction',
    description: "Introducing this feed, Andrew Grathwohl ruminates upon the artistic meaning behind the Sonic Multiplicities platform, and why it is so unfit for today's traditional distribution workflows. If you want to know why a serious composer and many serious musicians are all about releasing music via a podcast feed, give this brief narrative overture a gander. Never heard of Sonic Multiplicities before and want to know what the hell we're talking about? Check out our <a href='https://sonicmultiplicities.audio'>home page</a> at https://sonicmultiplicities.audio and brace yourself for its eery Geocities vibes.",
    url: 'https://s3.amazonaws.com/sonicmultiplicities.audio/feed/SM000.mp3',
    categories: ['Music'],
    guid: 'SM000',
    author: 'Andrew Grathwohl',
    date: 'October 11, 2019',
    'lat': latitude,
    'long': longitude,
    enclosure: {
      url: 'https://s3.amazonaws.com/sonicmultiplicities.audio/feed/SM000.mp3',
      file: '../releases/SM000.mp3',
      type: 'audio/mpeg'
    },
    itunesSummary: "Introducing this feed, Andrew Grathwohl ruminates upon the artistic meaning behind the Sonic Multiplicities platform, and why it is so unfit for today's traditional distribution workflows. If you want to know why a serious composer and many serious musicians are all about releasing music via a podcast feed, give this brief narrative overture a gander. Never heard of Sonic Multiplicities before and want to know what the hell we're talking about? Check out our <a href='https://sonicmultiplicities.audio'>home page</a> at https://sonicmultiplicities.audio and brace yourself for its eery Geocities vibes.",
    itunesSubtitle: 'Sonic Multiplicities introduction, by Andrew Grathwohl',
    itunesDuration: 114,
    itunesExplicit: false,
    itunesKeywords: ['music', 'experimental', 'avant-garde', 'electroacoustic', 'computer', 'linux', 'audio'],
    itunesTitle: 'SM000: Introduction',
    itunesImage: 'https://sonicmultiplicities.audio/triangle.png',
    itunesSeason: 2019,
    itunesEpisode: 1,
    itunesAuthor: 'Andrew Grathwohl',
    itunesEpisodeType: 'trailer'
  }, {
    title: 'SM001: Injection Time Lapse',
    description: '<b>Garrett Semmelink</b>: Violin, prepared violin, and hand percussion.<br>Check out the <b>music video</b> on <a href="https://vimeo.com/351832834">Vimeo</a>! Downloads: <a href="https://s3.amazonaws.com/sonicmultiplicities.audio/feed/downloads/SM001.flac">FLAC</a> & <a href="https://s3.amazonaws.com/sonicmultiplicities.audio/feed/downloads/SM001.opus">OPUS</a>',
    url: 'https://s3.amazonaws.com/sonicmultiplicities.audio/feed/SM001.mp3',
    categories: ['Music'],
    guid: 'SM001',
    author: 'Andrew Grathwohl',
    date: 'October 13, 2019',
    'lat': latitude,
    'long': longitude,
    enclosure: {
      url: 'https://s3.amazonaws.com/sonicmultiplicities.audio/feed/SM001.mp3',
      file: '../releases/SM001.mp3',
      type: 'audio/mpeg'
    },
    itunesSubtitle: 'We are so back! And we have new bad-ass music videos.',
    itunesDuration: 1595,
    itunesExplicit: false,
    itunesKeywords: ['music', 'experimental', 'avant-garde', 'electroacoustic', 'computer', 'linux', 'audio'],
    itunesTitle: 'SM001: Injection Time Lapse',
    itunesImage: 'https://s3.amazonaws.com/sonicmultiplicities.audio/feed/SM001.jpg',
    itunesSeason: 2019,
    itunesEpisode: 2,
    itunesSummary: '<b>Garrett Semmelink</b>: Violin, prepared violin, and hand percussion.<br>Check out the <b>music video</b> on <a href="https://vimeo.com/351832834">Vimeo</a>! Downloads: <a href="https://s3.amazonaws.com/sonicmultiplicities.audio/feed/downloads/SM001.flac">FLAC</a> & <a href="https://s3.amazonaws.com/sonicmultiplicities.audio/feed/downloads/SM001.opus">OPUS</a>',
    itunesAuthor: 'Andrew Grathwohl',
  },{
    title: 'SM002a: Music Ain\'t For Airports',
    description: '<b>Garrett Semmelink</b>: Violin, voice.<br>Check out the <b>music video</b> on <a href="https://vimeo.com/364915988">Vimeo</a>! Downloads: <a href="https://s3.amazonaws.com/sonicmultiplicities.audio/feed/downloads/SM002a.flac">FLAC</a> & <a href="https://s3.amazonaws.com/sonicmultiplicities.audio/feed/downloads/SM002a.opus">OPUS</a>',
    url: 'https://s3.amazonaws.com/sonicmultiplicities.audio/feed/SM002a.mp3',
    categories: ['Music'],
    guid: 'SM002a',
    author: 'Andrew Grathwohl',
    date: 'October 15, 2019',
    'lat': latitude,
    'long': longitude,
    enclosure: {
      url: 'https://s3.amazonaws.com/sonicmultiplicities.audio/feed/SM002a.mp3',
      file: '../releases/SM002a.mp3',
      type: 'audio/mpeg'
    },
    itunesSubtitle: 'Don\'t you forget it.',
    itunesDuration: 831,
    itunesExplicit: false,
    itunesKeywords: ['music', 'experimental', 'avant-garde', 'electroacoustic', 'computer', 'linux', 'audio'],
    itunesTitle: 'SM002a: Music Ain\'t For Airports',
    itunesImage: 'https://s3.amazonaws.com/sonicmultiplicities.audio/feed/SM002a.jpg',
    itunesSeason: 2019,
    itunesEpisode: 3,
    itunesSummary: '<b>Garrett Semmelink</b>: Violin, voice.<br>Check out the <b>music video</b> on <a href="https://vimeo.com/364915988">Vimeo</a>! Downloads: <a href="https://s3.amazonaws.com/sonicmultiplicities.audio/feed/downloads/SM002a.flac">FLAC</a> & <a href="https://s3.amazonaws.com/sonicmultiplicities.audio/feed/downloads/SM002a.opus">OPUS</a><br><b>Go to this piece\'s <a href="https://sonicmultiplicities.audio/music/SA002/">SM homepage</a></b>.<br>___MUSIC AIN\'T FOR AIRPORTS___<br>Think back to the last time you had to visit an airport in the United States. You\'re sitting in some brazenly uncomfortable airport bench, anxious from having just had your junk fondled by an old person pushing sixty in a blue uniform; annoyed by the hoards of people who take far more personal space than they require, and; overwhelmed by the slap echo hustle and bustle that seems to be present in every such complex of buildings. Only the deliberately psychopathic would dare look at such a scenario and suggest: "let\'s AstroTurf this environment with the playback of commercial music recordings. That should plug up this glaring hole of thoughtlessness, bureaucracy, and corruption." And yet, here we are.<br> Given all the events, which have transpired since 1978, one could easily conclude that music ain\'t for airports. However, hindsight being 20/20, it was perhaps essential that somebody conceived of such an exaggerated expansion in the size and scope of music\'s reach. For it is now exceedingly clear today, that the literate mind\'s tendency to disrespect the confines of music\'s glory, is on display in numerous social dilemmata.<br>Music may put more asses in the seats, more shoppers in the supermarket aisles, and more enthusiastic workers into boring office jobs - but what other human ingenuity have we tossed aside, which could have more adequately addressed such concerns? Worse yet, what has this severe mis-allocation of resources done to stall and disarm the lateral, multi-dimensional expansion of the sonic arts required for the survival and evolution of modern humanity?<br>Music can\'t solve our problems; it can only create new ones. It is our hope that you have a very, very troubled day after listening to this recording.',
    itunesAuthor: 'Andrew Grathwohl',

  },{
    title: 'SM002a: Introduction',
    description: "Introduction to Music Ain't For Airports, <a href='https://sonicmultiplicities.audio/music/SA002/'>SA002</a>, by Andrew Grathwohl",
    url: 'https://s3.amazonaws.com/sonicmultiplicities.audio/feed/SM002a_intro.mp3',
    categories: ['Music'],
    guid: 'SM002a_intro',
    author: 'Andrew Grathwohl',
    date: 'October 15, 2019',
    'lat': latitude,
    'long': longitude,
    enclosure: {
      url: 'https://s3.amazonaws.com/sonicmultiplicities.audio/feed/SM002a_intro.mp3',
      file: '../releases/SM002a_intro.mp3',
      type: 'audio/mpeg'
    },
    itunesSummary: "Introduction to Music Ain't For Airports, <a href='https://sonicmultiplicities.audio/music/SA002/'>SA002</a>, by Andrew Grathwohl",
    itunesSubtitle: 'SM002a introduction, by Andrew Grathwohl',
    itunesDuration: 124,
    itunesExplicit: false,
    itunesKeywords: ['music', 'experimental', 'avant-garde', 'electroacoustic', 'computer', 'linux', 'audio'],
    itunesTitle: 'SM002a: Introduction',
    itunesImage: 'https://s3.amazonaws.com/sonicmultiplicities.audio/feed/SM002a.jpg',
    itunesSeason: 2019,
    itunesEpisode: 3,
    itunesAuthor: 'Andrew Grathwohl',
    itunesEpisodeType: 'trailer'
  }].concat(oldTracks)
}
